import { assets } from "../../assets/assets";

const data = {
  concerts: [
    {
      id: "c1",
      type: "concert",
      image: assets.concert_1,
      heading: "Voice of Emotions",
      artist: "Arijit Singh",
      artistType: "Playback Singer",
      date: "2025-09-15",
      timing: {
        start: "19:00",
        end: "22:30",
      },
      location:
        "Netaji Indoor Stadium - 1, Stadium House, D.L. Khan Road, B.B.D. Bagh, Kolkata, West Bengal 700021",
      totalSeats: 5000,
      price: 2500,
      ageLimit: "10+",
      language: "Hindi",
      description:
        "Experience the magical voice of Arijit Singh in this unforgettable evening of melodies and emotions.",
      artistImage: "/images/artists/arijit-profile.jpg",
      artistBio:
        "India's most beloved playback singer known for romantic and soulful melodies.",
    },
    {
      id: "c2",
      type: "concert",
      image: assets.concert_2,
      heading: "Live with Energy",
      artist: "Diljit Dosanjh",
      artistType: "Punjabi Singer/Actor",
      date: "2025-11-20",
      timing: {
        start: "20:30",
        end: "23:45",
      },
      location:
        "Jawaharlal Nehru Stadium, Bhishma Pitamah Marg, New Delhi, Delhi 110003",
      totalSeats: 8000,
      price: 3000,
      ageLimit: "All Ages",
      language: "Punjabi",
      description:
        "High-energy performance with Punjabi beats and electrifying stage presence.",
      artistImage: "/images/artists/diljit-profile.jpg",
      artistBio:
        "International Punjabi singer and actor known for his vibrant performances.",
    },
    {
      id: "c3",
      type: "concert",
      image: assets.concert_3,
      heading: "A Night of Pure Magic",
      artist: "Coldplay",
      artistType: "International Band",
      date: "2025-12-12",
      timing: {
        start: "18:00",
        end: "21:30",
      },
      location:
        "DY Patil Stadium, Sector 7, Nerul, Navi Mumbai, Maharashtra 400706",
      totalSeats: 35000,
      price: 5000,
      ageLimit: "All Ages",
      language: "English",
      description:
        "Experience Coldplay's spectacular light show and greatest hits live.",
      artistImage: "/images/artists/coldplay-profile.jpg",
      artistBio:
        "Grammy-winning British rock band known for their anthemic hits.",
    },
    {
      id: "c4",
      type: "concert",
      image: assets.concert_4,
      heading: "Melodies of the Heart",
      artist: "Atif Aslam",
      artistType: "Singer-Songwriter",
      date: "2025-10-28",
      timing: {
        start: "19:30",
        end: "22:15",
      },
      location:
        "Indira Gandhi Athletic Stadium, Sarusajai, Guwahati, Assam 781025",
      totalSeats: 6000,
      price: 2200,
      ageLimit: "10+",
      language: "Urdu/Hindi",
      description:
        "An evening of soulful melodies with Atif Aslam's magical voice.",
      artistImage: "/images/artists/atif-profile.jpg",
      artistBio:
        "Pakistani singer known for his romantic ballads and powerful vocals.",
    },
    {
      id: "c5",
      type: "concert",
      image: assets.concert_5,
      heading: "Golden Hits Tour",
      artist: "Sonu Nigam",
      artistType: "Playback Singer",
      date: "2025-11-05",
      timing: {
        start: "20:00",
        end: "23:00",
      },
      location:
        "Shree Shiv Chhatrapati Sports Complex, Balewadi, Pune, Maharashtra 411045",
      totalSeats: 7000,
      price: 2800,
      ageLimit: "All Ages",
      language: "Hindi",
      description: "Relive the golden era of Bollywood music with Sonu Nigam.",
      artistImage: "/images/artists/sonu-profile.jpg",
      artistBio:
        "Versatile Indian playback singer with a career spanning decades.",
    },
    {
      id: "c6",
      type: "concert",
      image: assets.concert_6,
      heading: "Divine Melodies",
      artist: "Shreya Ghoshal",
      artistType: "Playback Singer",
      date: "2025-12-02",
      timing: {
        start: "18:30",
        end: "21:15",
      },
      location:
        "Gachibowli Indoor Stadium, Gachibowli, Hyderabad, Telangana 500032",
      totalSeats: 5500,
      price: 2300,
      ageLimit: "All Ages",
      language: "Hindi",
      description:
        "An enchanting evening with the queen of melodies, Shreya Ghoshal.",
      artistImage: "/images/artists/shreya-profile.jpg",
      artistBio: "National Award-winning playback singer with a divine voice.",
    },
    {
      id: "c7",
      type: "concert",
      image: assets.concert_7,
      heading: "AR Rahman Live",
      artist: "AR Rahman",
      artistType: "Music Composer",
      date: "2026-01-10",
      timing: {
        start: "19:00",
        end: "22:45",
      },
      location:
        "EKA Arena by TransStadia, University Road, Ahmedabad, Gujarat 380009",
      totalSeats: 10000,
      price: 4000,
      ageLimit: "All Ages",
      language: "Multilingual",
      description:
        "The Oscar-winning maestro presents his greatest compositions live.",
      artistImage: "/images/artists/arrahman-profile.jpg",
      artistBio: "Academy Award-winning composer and music producer.",
    },
    {
      id: "c8",
      type: "concert",
      image: assets.concert_8,
      heading: "Dance Beats Night",
      artist: "Neha Kakkar",
      artistType: "Playback Singer",
      date: "2025-11-15",
      timing: {
        start: "21:00",
        end: "23:30",
      },
      location: "Thyagaraj Sports Complex, INA Colony, New Delhi, Delhi 110023",
      totalSeats: 5000,
      price: 2000,
      ageLimit: "16+",
      language: "Hindi",
      description:
        "High-energy dance party with Neha Kakkar's chartbuster hits.",
      artistImage: "/images/artists/neha-profile.jpg",
      artistBio:
        "Bollywood's most popular female playback singer for dance numbers.",
    },
    {
      id: "c9",
      type: "concert",
      image: assets.concert_9,
      heading: "Hip Hop King Live",
      artist: "Badshah",
      artistType: "Rapper",
      date: "2025-12-20",
      timing: {
        start: "22:00",
        end: "01:00",
      },
      location:
        "Bandra Kurla Complex Ground, Bandra East, Mumbai, Maharashtra 400051",
      totalSeats: 8000,
      price: 2500,
      ageLimit: "18+",
      language: "Hindi/Punjabi",
      description:
        "India's hip-hop sensation Badshah brings his high-octane performance.",
      artistImage: "/images/artists/badshah-profile.jpg",
      artistBio:
        "Rapper, singer and composer known for his chart-topping party tracks.",
    },
  ],
  comedy: [
    {
      id: "cm1",
      type: "comedy",
      image: assets.comedy_1,
      heading: "Zakir Khan – Sakht Launda",
      artist: "Zakir Khan",
      artistType: "Stand-up Comedian",
      date: "2025-09-25",
      timing: {
        start: "19:30",
        end: "22:00",
      },
      location:
        "Kamani Auditorium, Copernicus Marg, Mandi House, New Delhi, Delhi 110001",
      totalSeats: 1500,
      price: 1500,
      ageLimit: "18+",
      language: "Hindi",
      description:
        "Zakir Khan brings his unique style of storytelling and relatable humor.",
      artistImage: "/images/artists/zakir-profile.jpg",
      artistBio:
        "Stand-up comedian known for his 'sakht launda' persona and relatable humor.",
    },
    {
      id: "cm2",
      type: "comedy",
      image: assets.comedy_2,
      heading: "Samay Raina – Cracks You Up",
      artist: "Samay Raina",
      artistType: "Chess Comedian",
      date: "2025-10-10",
      timing: {
        start: "20:00",
        end: "22:30",
      },
      location: "Ravindra Bharathi, Saifabad, Hyderabad, Telangana 500004",
      totalSeats: 1200,
      price: 1200,
      ageLimit: "16+",
      language: "Hindi/English",
      description:
        "Chess comedian Samay Raina with his unique blend of chess and comedy.",
      artistImage: "/images/artists/samay-profile.jpg",
      artistBio: "Chess streamer turned comedian known for his quick wit.",
    },
    {
      id: "cm3",
      type: "comedy",
      image: assets.comedy_3,
      heading: "Munawar Faruqui – Live On Stage",
      artist: "Munawar Faruqui",
      artistType: "Stand-up Comedian",
      date: "2025-11-15",
      timing: {
        start: "21:00",
        end: "23:15",
      },
      location:
        "Sirifort Auditorium, August Kranti Marg, New Delhi, Delhi 110049",
      totalSeats: 2000,
      price: 1800,
      ageLimit: "18+",
      language: "Hindi",
      description: "Munawar's observational comedy with a touch of dark humor.",
      artistImage: "/images/artists/munawar-profile.jpg",
      artistBio: "Comedian known for his intelligent and bold humor.",
    },
    {
      id: "cm4",
      type: "comedy",
      image: assets.comedy_4,
      heading: "Abish Mathew – Son of Abish",
      artist: "Abish Mathew",
      artistType: "Musical Comedian",
      date: "2025-10-22",
      timing: {
        start: "19:00",
        end: "21:15",
      },
      location:
        "Chowdiah Memorial Hall, 16th Cross, Vyalikaval, Bangalore, Karnataka 560003",
      totalSeats: 1000,
      price: 1300,
      ageLimit: "16+",
      language: "English/Hindi",
      description: "Musical comedy with Abish's signature style and improv.",
      artistImage: "/images/artists/abish-profile.jpg",
      artistBio: "Musical comedian and host known for his improv skills.",
    },
    {
      id: "cm5",
      type: "comedy",
      image: assets.comedy_5,
      heading: "Akash Gupta – Gandu Engineer",
      artist: "Akash Gupta",
      artistType: "Stand-up Comedian",
      date: "2025-11-08",
      timing: {
        start: "20:30",
        end: "22:30",
      },
      location:
        "Siri Fort Auditorium, August Kranti Marg, New Delhi, Delhi 110049",
      totalSeats: 1800,
      price: 1400,
      ageLimit: "18+",
      language: "Hindi",
      description:
        "Akash's hilarious take on engineering life and relationships.",
      artistImage: "/images/artists/akash-profile.jpg",
      artistBio:
        "Engineer-turned-comedian known for his 'Gandu Engineer' persona.",
    },
    {
      id: "cm6",
      type: "comedy",
      image: assets.comedy_6,
      heading: "Kaneez Surka – Improv Queen",
      artist: "Kaneez Surka",
      artistType: "Improv Comedian",
      date: "2025-12-05",
      timing: {
        start: "19:30",
        end: "21:45",
      },
      location:
        "St. Andrews Auditorium, Bandra West, Mumbai, Maharashtra 400050",
      totalSeats: 1500,
      price: 1500,
      ageLimit: "16+",
      language: "English/Hindi",
      description:
        "Interactive improv comedy show with audience participation.",
      artistImage: "/images/artists/kaneez-profile.jpg",
      artistBio: "India's queen of improv comedy and character acts.",
    },
    {
      id: "cm7",
      type: "comedy",
      image: assets.comedy_7,
      heading: "Rahul Subramanian – Kal Main Udega",
      artist: "Rahul Subramanian",
      artistType: "Corporate Comedian",
      date: "2025-11-25",
      timing: {
        start: "20:00",
        end: "22:15",
      },
      location:
        "G.D. Birla Sabhagar, 9/2, R.N. Mukherjee Road, Kolkata, West Bengal 700001",
      totalSeats: 1200,
      price: 1200,
      ageLimit: "16+",
      language: "Hindi/English",
      description: "Rahul's corporate comedy with hilarious life observations.",
      artistImage: "/images/artists/rahul-profile.jpg",
      artistBio: "Ex-marketer turned comedian known for his corporate humor.",
    },
    {
      id: "cm8",
      type: "comedy",
      image: assets.comedy_8,
      heading: "Anish Joshi – Gujju Gone Wrong",
      artist: "Anish Joshi",
      artistType: "Cultural Comedian",
      date: "2025-12-15",
      timing: {
        start: "21:00",
        end: "23:00",
      },
      location:
        "Sardar Vallabhbhai Patel Indoor Stadium, Marine Drive, Mumbai, Maharashtra 400020",
      totalSeats: 2000,
      price: 1600,
      ageLimit: "18+",
      language: "Hindi/English",
      description: "Anish's hilarious take on Gujju culture and NRIs.",
      artistImage: "/images/artists/anish-profile.jpg",
      artistBio: "Gujarati comedian known for his NRI and cultural humor.",
    },
    {
      id: "cm9",
      type: "comedy",
      image: assets.comedy_9,
      heading: "Kenny Sebastian – Don't Be That Guy",
      artist: "Kenny Sebastian",
      artistType: "Musical Comedian",
      date: "2026-01-05",
      timing: {
        start: "20:30",
        end: "22:45",
      },
      location:
        "Phoenix Marketcity, Mahadevapura, Whitefield Road, Bangalore, Karnataka 560048",
      totalSeats: 2500,
      price: 2000,
      ageLimit: "16+",
      language: "English/Hindi",
      description: "Kenny's musical comedy with relatable everyday humor.",
      artistImage: "/images/artists/kenny-profile.jpg",
      artistBio: "Multitalented comedian, musician and filmmaker.",
    },
  ],
  sports: [
    {
      id: "s1",
      type: "sports",
      image: assets.sports_1,
      heading: "IPL Championship 2025",
      teams: [
        {
          name: "Mumbai Indians",
          logo: "/images/teams/mi-logo.png",
          playerType: "Cricket Team",
        },
        {
          name: "Chennai Super Kings",
          logo: "/images/teams/csk-logo.png",
          playerType: "Cricket Team",
        },
      ],
      date: "2025-09-14",
      timing: {
        start: "19:30",
        end: "23:00",
      },
      location:
        "Wankhede Stadium, 'D' Road, Churchgate, Mumbai, Maharashtra 400020",
      totalSeats: 35000,
      price: 2000,
      ageLimit: "All Ages",
      language: "N/A",
      description:
        "Witness the clash of titans in this year's IPL championship finals.",
      sportType: "Cricket",
    },
    {
      id: "s2",
      type: "sports",
      image: assets.sports_2,
      heading: "International Football Friendly",
      teams: [
        {
          name: "India National Team",
          logo: "/images/teams/india-logo.png",
          playerType: "Football Team",
        },
        {
          name: "Brazil National Team",
          logo: "/images/teams/brazil-logo.png",
          playerType: "Football Team",
        },
      ],
      date: "2025-11-20",
      timing: {
        start: "17:00",
        end: "19:30",
      },
      location:
        "Jawaharlal Nehru Stadium, Bhishma Pitamah Marg, New Delhi, Delhi 110003",
      totalSeats: 50000,
      price: 1500,
      ageLimit: "All Ages",
      language: "N/A",
      description:
        "An exciting international friendly match featuring football legends.",
      sportType: "Football",
    },
    {
      id: "s3",
      type: "sports",
      image: assets.sports_3,
      heading: "Pro Kabaddi League Finals",
      teams: [
        {
          name: "Patna Pirates",
          logo: "/images/teams/patna-logo.png",
          playerType: "Kabaddi Team",
        },
        {
          name: "Bengal Warriors",
          logo: "/images/teams/bengal-logo.png",
          playerType: "Kabaddi Team",
        },
      ],
      date: "2025-10-30",
      timing: {
        start: "20:00",
        end: "22:30",
      },
      location: "Thyagaraj Sports Complex, INA Colony, New Delhi, Delhi 110023",
      totalSeats: 10000,
      price: 1000,
      ageLimit: "All Ages",
      language: "N/A",
      description: "High-intensity kabaddi action in the PKL season finale.",
      sportType: "Kabaddi",
    },
    {
      id: "s4",
      type: "sports",
      image: assets.sports_4,
      heading: "India Open Badminton Championship",
      players: [
        {
          name: "PV Sindhu",
          country: "India",
          playerType: "Badminton Player",
        },
        {
          name: "Kento Momota",
          country: "Japan",
          playerType: "Badminton Player",
        },
      ],
      date: "2025-12-10",
      timing: {
        start: "10:00",
        end: "18:00",
      },
      location: "Indira Gandhi Arena, Kashmere Gate, New Delhi, Delhi 110002",
      totalSeats: 8000,
      price: 1200,
      ageLimit: "All Ages",
      language: "N/A",
      description:
        "Watch top international badminton players compete for the India Open title.",
      sportType: "Badminton",
    },
    {
      id: "s5",
      type: "sports",
      image: assets.sports_5,
      heading: "International Premier Tennis League",
      players: [
        {
          name: "Rafael Nadal",
          country: "Spain",
          playerType: "Tennis Player",
        },
        {
          name: "Serena Williams",
          country: "USA",
          playerType: "Tennis Player",
        },
      ],
      date: "2026-01-20",
      timing: {
        start: "16:00",
        end: "21:00",
      },
      location:
        "Kanteerava Indoor Stadium, Kasturba Road, Bangalore, Karnataka 560001",
      totalSeats: 6000,
      price: 2500,
      ageLimit: "All Ages",
      language: "N/A",
      description:
        "Tennis legends compete in this exciting team format tournament.",
      sportType: "Tennis",
    },
    {
      id: "s6",
      type: "sports",
      image: assets.sports_6,
      heading: "Hockey World League Finals",
      teams: [
        {
          name: "India National Team",
          logo: "/images/teams/india-logo.png",
          playerType: "Hockey Team",
        },
        {
          name: "Australia National Team",
          logo: "/images/teams/australia-logo.png",
          playerType: "Hockey Team",
        },
      ],
      date: "2026-01-05",
      timing: {
        start: "18:00",
        end: "20:30",
      },
      location:
        "Birsa Munda International Hockey Stadium, Rourkela, Odisha 769004",
      totalSeats: 20000,
      price: 800,
      ageLimit: "All Ages",
      language: "N/A",
      description:
        "Top international hockey teams compete in this prestigious tournament.",
      sportType: "Hockey",
    },
    {
      id: "s7",
      type: "sports",
      image: assets.sports_7,
      heading: "Pro Wrestling League Finals",
      teams: [
        {
          name: "Delhi Sultans",
          logo: "/images/teams/delhi-logo.png",
          playerType: "Wrestling Team",
        },
        {
          name: "Mumbai Garuda",
          logo: "/images/teams/mumbai-logo.png",
          playerType: "Wrestling Team",
        },
      ],
      date: "2025-11-12",
      timing: {
        start: "19:30",
        end: "22:00",
      },
      location:
        "KD Jadhav Indoor Hall, Indira Gandhi Stadium Complex, New Delhi, Delhi 110002",
      totalSeats: 5000,
      price: 1000,
      ageLimit: "10+",
      language: "N/A",
      description:
        "High-flying action in the professional wrestling league finals.",
      sportType: "Wrestling",
    },
    {
      id: "s8",
      type: "sports",
      image: assets.sports_8,
      heading: "NBA India Games 2025",
      teams: [
        {
          name: "Sacramento Kings",
          logo: "/images/teams/kings-logo.png",
          playerType: "Basketball Team",
        },
        {
          name: "Indiana Pacers",
          logo: "/images/teams/pacers-logo.png",
          playerType: "Basketball Team",
        },
      ],
      date: "2025-12-05",
      timing: {
        start: "19:00",
        end: "21:30",
      },
      location: "NSCI Dome, Worli, Mumbai, Maharashtra 400018",
      totalSeats: 8000,
      price: 5000,
      ageLimit: "All Ages",
      language: "N/A",
      description:
        "NBA teams play preseason games in India for the first time.",
      sportType: "Basketball",
    },
    {
      id: "s9",
      type: "sports",
      image: assets.sports_9,
      heading: "World Boxing Championship",
      players: [
        {
          name: "Mary Kom",
          country: "India",
          playerType: "Boxer",
        },
        {
          name: "Claressa Shields",
          country: "USA",
          playerType: "Boxer",
        },
      ],
      date: "2026-02-15",
      timing: {
        start: "17:00",
        end: "21:00",
      },
      location: "Kalinga Stadium, Nayapalli, Bhubaneswar, Odisha 751012",
      totalSeats: 12000,
      price: 1500,
      ageLimit: "12+",
      language: "N/A",
      description:
        "Elite boxers from around the world compete for world championship titles.",
      sportType: "Boxing",
    },
  ],
};

export default data;
